swagger: 2.0
info:
  title: "Github webhook API"
consumes:
  - application/json
produces:
  - application/json
paths:
  /:
    post:
      x-amazon-apigateway-integration:
        httpMethod: post
        type: aws
        requestTemplates:
          application/json: "$util.base64Encode($input.body)"
